name: Test compilation

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs: {}

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opam_file:
          - 'coq-verified-extraction.opam'
        image:
          - 'yforster/coq:8.19.1--clang-11--compcert-3.13.1--extlib-0.12.1--equations-1.3--metacoq-1.3.1'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          opam_file: ${{ matrix.opam_file }}
          before_install: |
            startGroup "fix permission issues"
              sudo chown -R coq:coq .
            endGroup
          install: |
            startGroup "make"
              make
            endGroup
          script: 
          after_install:
          after_script:
          uninstall:
